### ISSUE TITLE
Startup script-defined signals/pseudopositioners are skipped by discovery mechanism

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcdsdevices_notepad#8]
* Startup script-defined signals/pseudopositioners are not in happi
* Such signals will be skipped by this discovery script

Thoughts:
* Is it sufficient to force devices to be moved to happi? Or, do we need some additional discovery mechanism?
* Alternatively, maybe notepad signals could disable themselves if not associated with a happi device?

cc @ZryletTC @ZLLentz

**Comment by ZLLentz** [comment]
- I think it's fine to require these to exist in `happi` to get the full feature set. The only other discovery mechanism I can think of is having notepad signals register with a server process...
- Notepad signals should ignore the PV if they aren't in `happi`, or else we get situations where you can't use these pseudopositioners properly in testing, etc.
- In general I think ophyd is (intentionally?) missing support for these "crazier" use-cases where you want to ignore a disconnected PV (or ignore a component based on initialization parameters or startup discoveries)

**Comment by klauer** [comment]
OK, I'll see about modifying the signal to check for happi's metadata key on the root device.

You're right on point (3), @ZLLentz - it is that way by design and will require some hacking. Something along the lines of stashing a signal for optional use and proxying the original when available, perhaps.

**Comment by ZLLentz** [comment]
Some more thought, it might be possible to create a `MaybeEpicsSignal` kind of class where if certain conditions are met it tries to connect to the PV, and otherwise just acts like a `Signal`... could be useful. Could be dangerous.

**Comment by klauer** [comment]
Same wavelength again, @ZLLentz - I'm poking around with one called `_OptionalEpicsSignal` at the moment... Am indeed a bit scared of what it could be used for.

**Comment by klauer** [comment]
ref. https://github.com/pcdshub/pcdsdevices/pull/508/commits/4636fb6469c6d441766a6abfdea3b7951e99def1

**Comment by klauer** [comment]
Closed in https://github.com/pcdshub/pcdsdevices/pull/508
